id: A8084EBFF
title: In Praise of Jigme Lingpa’s Pre-Eminence
type: translation
pechas:
- I44B983F4
- I136A5735
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:21.666140
  last_modified_at: 2023-01-04 12:43:21.666157
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I44B983F4/4896: 7F7C
  I136A5735/24A7: 7F7C
